name: ci

on:
   push:
      branches:
         - master
   pull_request:

jobs:
   ci:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '14'
              cache: 'yarn'

         - name: install
           id: install
           run: |
              yarn install --frozen-lockfile

         - id: lint
           name: lint
           run: |
              yarn lint

         - id: cover
           name: cover
           run: |
              yarn cover

         - id: build
           name: build
           run: |
              yarn build
